//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestor_de_Siniestros.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dictamenes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dictamenes()
        {
            this.Reportes = new HashSet<Reportes>();
        }
    
        public int idDictamen { get; set; }
        public int delegacion { get; set; }
        public string estado { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> perito { get; set; }
        public System.DateTime fechaHora { get; set; }
    
        public virtual Delegaciones Delegaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reportes> Reportes { get; set; }
    }
}
