//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestor_de_Siniestros.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportesFotografias
    {
        public int idReporteFotografia { get; set; }
        public int idReporte { get; set; }
        public byte[] fotoUno { get; set; }
        public byte[] fotoDos { get; set; }
        public byte[] fotoTres { get; set; }
        public byte[] fotoCuatro { get; set; }
        public byte[] fotoCinco { get; set; }
        public byte[] fotoSeis { get; set; }
        public byte[] fotoSiete { get; set; }
        public byte[] fotoOcho { get; set; }
    
        public virtual Reportes Reportes { get; set; }
    }
}
