//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestor_de_Siniestros.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reportes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reportes()
        {
            this.ReportesFotografias = new HashSet<ReportesFotografias>();
            this.ReportesUsuarios = new HashSet<ReportesUsuarios>();
            this.ReportesVehiculos = new HashSet<ReportesVehiculos>();
        }
    
        public int idReporte { get; set; }
        public string direccion { get; set; }
        public int idDictamen { get; set; }
        public System.DateTime fechaReporte { get; set; }
        public string creador { get; set; }
    
        public virtual Dictamenes Dictamenes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportesFotografias> ReportesFotografias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportesUsuarios> ReportesUsuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportesVehiculos> ReportesVehiculos { get; set; }
    }
}
